### ISSUE TITLE
无效

### ISSUE THREAD

**Issue by nullkk** [zly394/CollapsedTextView#2]
代码中设置

   `     tvInfo.setText("你还你还地球你还你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方你还地球第三方");//设置简介
`
并没有效果...但是在xml里面设置就起作用了?why

**Comment by zly394** [comment]
@nullkk 使用 java 代码设置时不要在 xml 文件里再设置了

**Comment by zly394** [comment]
新版已修复

**Comment by nullkk** [comment]
感谢楼主,之前的问题修复了. 能不能提个建议 就是当文字是满屏平排的时候 (就是正好是5行平排的时候) 能不能计算下 收起箭头的距离 

![23232](https://user-images.githubusercontent.com/20369464/29546764-c25a2200-8728-11e7-8f38-8fb27d850a8d.png)
